#!/bin/bash
sleep 0.5

pkill eww
pkill python

eww daemon
eww open dock

sleep 0.5
python $XDG_CONFIG_HOME/eww/scripts/apps.py --query &
sleep 0.9
eww update dock_rev=true
sleep 0.9
eww update dock_rev=false
