#!/bin/bash

toggle_menu() {
  if [[ $(eww windows | grep -w '*notifications') ]]; then
    eww close notifications
    eww open menu
  else
    eww open --toggle menu
  fi
}

toggle_launcher() {
  if [[ $(eww windows | grep '*launcher') ]]; then
    eww close launcher
    python $XDG_CONFIG_HOME/eww/scripts/apps.py --query
  else
    eww open launcher
    python $XDG_CONFIG_HOME/eww/scripts/apps.py --query
  fi
}

toggle_bar() {
  if [[ -z $(eww windows | grep '*bar') ]]; then
    sed -i '2{s/^#//}' ~/.config/hypr/settings.conf
    eww open bar
  else
    sed -i '2{s/^/#/}' ~/.config/hypr/settings.conf
    eww close bar
  fi
}

main() {
  if [[ -z $(pidof eww) ]]; then
    eww daemon
    toggle_bar
  else
    toggle_bar
  fi

}

case $1 in
--menu)
  toggle_menu
  ;;
--launcher)
  toggle_launcher
  ;;
--bar)
  main
  ;;
esac
