#!/bin/bash

toggle_menu() {
  if [[ $(eww active-windows | grep launcher) ]]; then
    eww close launcher
  fi
  eww open --toggle menu
}

toggle_launcher() {
  if [[ $(eww active-windows | grep menu) ]]; then
    eww close menu
  fi

  eww open --toggle launcher
  ~/.config/eww/scripts/apps.py --query
}

toggle_bar() {
  eww open --toggle bar
}

toggle_vpn() {
  cd ~/.config/mihomo
  pkill mihomo
  file="config.yaml"
  if grep -q "enable: true" $file; then
    sed -i 's/enable: true/enable: false/' $file
    eww update vpn=off
  else
    sed -i 's/enable: false/enable: true/' $file
    eww update vpn=on
  fi
  mihomo > /dev/null 2>&1 &
}

case $1 in
--menu)
  toggle_menu
  ;;
--launcher)
  toggle_launcher
  ;;
--bar)
  toggle_bar
  ;;
--vpn)
  toggle_vpn
  ;;
esac
