#!/bin/bash

vol="$(eww get volumeval)"

if [[ -z $(eww active-windows | grep 'volume') ]]; then
  eww open volume
fi

while true; do
  sleep 0.6

  new_vol=$(eww get volumeval)

  if [ "$vol" != "$new_vol" ]; then
    vol="$new_vol"
  else
    newest_vol=$(eww get volumeval)
    if [ "$vol" == "$newest_vol" ]; then
      if [[ -n $(eww active-windows | grep 'volume') ]];then
        eww close volume;
        exit
      fi
    fi
  fi
done
