#!/bin/bash

DATE="$(date +'%d-%m-%y_%H:%M:%S')"
DIR="$HOME/Pictures/Screenshots"
PIC="$DIR/$DATE.png"

[ ! -d "$DIR" ] && mkdir -pv "$DIR"

full() {
  grim -l 1 "$PIC"
  copyq copy image/png - < $PIC
}

crop() {
  pgrep slurp || grim -l 1 -g "$(slurp)" "$PIC"
  copyq copy image/png - < $PIC
}

case "$1" in
--full)
  full
  notify-send -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
  ;;
--crop)
  crop
  notify-send -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
  ;;
esac
