#!/bin/bash

DATE="$(date +'%d-%m-%y_%H:%M:%S')"
DIR="$HOME/Pictures/Screenshots"
PIC="$DIR/$DATE.png"

[ ! -d "$DIR" ] && mkdir -pv "$DIR"

full() {
  grim -l 1 "$PIC"
}

crop() {
  pgrep slurp || grim -l 1 -g "$(slurp)" "$PIC"
}

abort() {
  notify-send -a "Screenshot info" -i dialog-error "Screenshot" "aborted"
  exit 1
}

case "$1" in
--full)
  full || abort
  wl-copy < "$PIC"
  notify-send -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
  ;;
--crop)
  crop || abort
  wl-copy < "$PIC"
  notify-send -u low -a Screenshot -i "$PIC" "Copied to clipboard" "$PIC"
  ;;
esac
